#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# Author: Serg Kolo , contact: 1047481448@qq.com
# Date: September 27 , 2016
# Purpose: appindicator for displaying mounted filesystem usage
# Tested on: Ubuntu 16.04 LTS
#
#
# Licensed under The MIT License (MIT).
# See included LICENSE file or the notice below.
#
# Copyright © 2016 Sergiy Kolodyazhnyy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
import gi
gi.require_version('AppIndicator3', '0.1')
from gi.repository import GLib as glib
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Gtk as gtk
from gi.repository import Gio
from os import statvfs
#from collections import OrderedDict
import subprocess
import shutil
import dbus
import json
import os

class UdisksIndicator(object):

    def __init__(self):
        self.app = appindicator.Indicator.new(
            'udisks-indicator', "drive-harddisk-symbolic.svg",
            appindicator.IndicatorCategory.HARDWARE
            )

        if not self.app.get_icon():
           self.app.set_icon("drive-harddisk-symbolic")

        self.app.set_status(appindicator.IndicatorStatus.ACTIVE)

        filename = '.partition_aliases.json'
        user_home = os.path.expanduser('~')
        self.config_file = os.path.join(user_home,filename)
        self.cache = self.get_partitions()
        self.make_menu()
        self.update()


    def update(self):
        timeout = 5
        glib.timeout_add_seconds(timeout,self.callback)

    def callback(self):
        current = self.get_partitions()
        if self.cache != current:
            self.cache = current
            self.make_menu()
        self.update()        

    def add_menu_item(self,menu_obj,item_type,image,label,action,args):
        menu_item,icon = None,None
        if item_type is gtk.ImageMenuItem and label:
            menu_item = gtk.ImageMenuItem.new_with_label(label)
            menu_item.set_always_show_image(True)
            if '/' in image:
                icon = gtk.Image.new_from_file(image)
            else:
                icon = gtk.Image.new_from_icon_name(image,16)
            menu_item.set_image(icon)
        elif item_type is gtk.ImageMenuItem and not label:
            menu_item = gtk.ImageMenuItem()
            menu_item.set_always_show_image(True)
            if '/' in image:
                icon = gtk.Image.new_from_file(image)
            else:
                icon = gtk.Image.new_from_icon_name(image,16)
            menu_item.set_image(icon)
        elif item_type is gtk.MenuItem:
            menu_item = gtk.MenuItem(label)
        elif item_type is gtk.SeparatorMenuItem:
            menu_item = gtk.SeparatorMenuItem()
        if action:
            menu_item.connect('activate',action,*args)

        menu_obj.append(menu_item)
        menu_item.show()

    def get_fields(self,*args):
        """ Returns info field items necessary for
            each entry, padded depending on 
            the system font used - default or monospace.
            Other font types are not covered
        """
            
        fields = ['Partition:','Alias:','Drive:',
                  'MountPoint:','Filesystem:','Usage:'
        ]

        if args[-1] == 'default':
            # Thanks to Mateo for figuring out these numbers
            fields[0] = fields[0] + " "*11
            fields[1] = fields[1] + " "*20
            fields[2] = fields[2] + " "*19
            fields[3] = fields[3] + " "*4
            fields[4] = fields[4] + " "*8
            fields[5] = fields[5] + " "*18

        if args[-1] == 'mono':
            for index,item in enumerate(fields):
                fields[index] = self.pad_string(item,20," ")

        return fields


    def make_menu(self,*args):
        """ generates entries in the indicator"""
        if hasattr(self, 'app_menu'):
            for item in self.app_menu.get_children():
                self.app_menu.remove(item)

        self.app_menu = gtk.Menu()

        partitions = self.get_partitions()

        font = self.gsettings_get('org.gnome.desktop.interface',None,'font-name')
        font = str(font).replace("'","") 
        fields = []
        if 'Ubuntu' in font and font.split()[1].isdigit():
            fields = self.get_fields('default')
        elif 'Mono' in font:
            fields = self.get_fields('mono')
        else:
            fields = self.get_fields('neither')
         
 
        
        for i in partitions:
            label_lines = [None]*6
            label_lines[0] = fields[0] + i[0]
            label_lines[2] = fields[2] + i[1]
            label_lines[3] = fields[3] + i[2]
            label_lines[5] = fields[5] + i[3] + "%"

            fill = float(i[3]) 
            fill = int(fill/10)
            # \u25A7 and \u25A1; maybe 2588
            #usage_bar = '\n' + u'\u2593'*fill + u'\u2591'*(10-fill)
            usage_bar = u'\u2588'*fill + u'\u2592'*(10-fill)

            # TODO: rewrite repetitive parts into nice function
            fs_type = str(self.get_filesystem_type(i[0]))
            if fs_type:
               label_lines[4] = fields[4] +  fs_type
            else:
               label_lines[4] = fields[4] +  "unknown"

            alias = self.find_alias(i[0])
            if alias:
                label_lines[1] = fields[1] + alias
            else:
                label_lines.pop(1)

            label_lines.append(usage_bar)
            label = '\n'.join(label_lines)

            
            icon = 'drive-harddisk'            
            self.add_menu_item(
                 self.app_menu,gtk.ImageMenuItem,
                 icon,label,
                 self.open_mountpoint,[i[2]]
            )       

#            self.menu_item = gtk.MenuItem(item)
#            self.menu_item.connect('activate',self.open_mountpoint,i[2])
#            self.app_menu.append(self.menu_item)
#            self.menu_item.show()

            self.separator = gtk.SeparatorMenuItem()
            self.app_menu.append(self.separator)
            self.separator.show()

        self.unmounted = gtk.MenuItem('Unmounted Partitions')
        self.unmounted_submenu = gtk.Menu()
        self.unmounted.set_submenu(self.unmounted_submenu)

        for i in self.get_unmounted_partitions():

            # TODO: add type checking, prevent swap
            # org.freedesktop.UDisks2.Block.IdType

            part = "Partition: " + i[0]
            alias = self.find_alias(i[0])
            drive = "\nDrive: " + i[1]
            fs_type = str(self.get_filesystem_type(i[0]))

            icon = None
            if fs_type:
               filesystem = "\nFilesystem: " + fs_type
               #icon = 'drive-removable-media'
              # icon = 'drive-multidisk'
               icon = 'drive-harddisk-system'
               if fs_type == 'swap':
                  filesystem = filesystem + " NOT MOUNTABLE"
                  icon = 'dialog-error'
               if 'iso' in fs_type:
                  icon = 'media-optical'
            else:
               filesystem = "\nFilesystem: unknown"

            bus_type = self.get_dbus_property(
                       'system','org.freedesktop.UDisks2',
                       '/org/freedesktop/UDisks2/drives/' + i[1],
                       'org.freedesktop.UDisks2.Drive','ConnectionBus'
            )

            if  bus_type == 'usb':
                icon = 'drive-removable-media-usb'

            label = part + drive + filesystem

            if alias: 
               alias = "\nAlias: " + alias
               label = part + alias + drive + filesystem

            
            self.add_menu_item(
                 self.unmounted_submenu,gtk.ImageMenuItem,
                 icon,label,
                 self.mount_partition,[i[0]]
            )       
#            self.menu_item = gtk.MenuItem(label)
#            self.menu_item.connect('activate',self.mount_partition,i[0])
#            self.unmounted_submenu.append(self.menu_item)
#            self.menu_item.show()
            self.add_menu_item(
                 self.unmounted_submenu,gtk.SeparatorMenuItem,
                 None,None,
                 None,[None]
            )
#            self.separator = gtk.SeparatorMenuItem()
#            self.unmounted_submenu.append(self.separator)
#            self.separator.show()

        self.app_menu.append(self.unmounted)
        self.unmounted.show()

        
        self.separator = gtk.SeparatorMenuItem()
        self.app_menu.append(self.separator)
        self.separator.show()

        self.make_part_alias = gtk.MenuItem('Make Alias')
        self.make_part_alias.connect('activate',self.make_alias)
        self.app_menu.append(self.make_part_alias)
        self.make_part_alias.show()
 
        user_home = os.path.expanduser('~')
        desktop_file = '.config/autostart/udisks-indicator.desktop'
        full_path = os.path.join(user_home,desktop_file)

        label = 'Start Automatically' 
        if os.path.exists(full_path):
           label = label + ' \u2714'
        self.autostart = gtk.MenuItem(label)
        self.autostart.connect('activate',self.toggle_auto_startup)
        self.app_menu.append(self.autostart)
        self.autostart.show()
        
        self.open_gnome_disks = gtk.ImageMenuItem.new_with_label('Open Disks Utility')
        self.open_gnome_disks.set_image(gtk.Image.new_from_icon_name('gnome-disks',16))
        self.open_gnome_disks.set_always_show_image(True)

        self.open_gnome_disks.connect('activate',self.open_disks_utility)
        self.app_menu.append(self.open_gnome_disks)
        self.open_gnome_disks.show()
 
        self.quit_app = gtk.MenuItem('Quit')
        self.quit_app.connect('activate', self.quit)
        self.app_menu.append(self.quit_app)
        self.quit_app.show()

        self.app.set_menu(self.app_menu)

    def pad_string(self,orig,length,pad):
        """ Pads characters to string to make it 
            have specific length and returns it"""
        return orig + pad*(length - len(orig))


    def mount_partition(self,*args):
        # TODO: implement error checking for mounting
        return self.run_cmd(['udisksctl','mount','-b','/dev/' + args[-1]])

    def get_filesystem_type(self,dev):
        args = ['system',
                'org.freedesktop.UDisks2',
                '/org/freedesktop/UDisks2/block_devices/' + dev,
                'org.freedesktop.UDisks2.Block',
                'IdType'
        ]
        try:
            return str(self.get_dbus_property(*args))
        except Exception as e:
            print(str(e))
            return None
            

    def get_mountpoint_usage(self,mountpoint):
        fs = statvfs(mountpoint)
        usage = 100*(float(fs.f_blocks)-float(fs.f_bfree))/float(fs.f_blocks)
        return str("{0:.2f}".format(usage))

    def get_partitions(self):
        objects = self.get_dbus('system', 
                           'org.freedesktop.UDisks2', 
                           '/org/freedesktop/UDisks2', 
                           'org.freedesktop.DBus.ObjectManager',
                           'GetManagedObjects',
                           None)
        
        
        partitions = []
        for item in objects:
            try:
                if 'block_devices'  in str(item):
                       
        
                       drive = self.get_dbus_property('system',
                                        'org.freedesktop.UDisks2',
                                        item,
                                        'org.freedesktop.UDisks2.Block',
                                        'Drive')
                       if drive == '/': continue
                      
                       mountpoint = self.get_mountpoint(item)
                       if not mountpoint: continue
                       mountpoint = mountpoint.replace('\x00','')
    
                       drive = str(drive).split('/')[-1]
                       usage = self.get_mountpoint_usage(mountpoint)

                       part = str(item.split('/')[-1])
                       partitions.append((part,drive,mountpoint,usage))                       

            except:
                pass

        # returning list of tuples
        partitions.sort()
        return partitions

    def get_mountpoint(self,dev_path):
        try:
            data = self.get_dbus_property(
                             'system',
                             'org.freedesktop.UDisks2',
                             dev_path,
                             'org.freedesktop.UDisks2.Filesystem',
                             'MountPoints')[0]
    
        except:
            return None
        else:
            if len(data) > 0:
                return ''.join([ chr(byte) for byte in data])


    def get_unmounted_partitions(self):
        objects = self.get_dbus('system', 
                           'org.freedesktop.UDisks2', 
                           '/org/freedesktop/UDisks2', 
                           'org.freedesktop.DBus.ObjectManager',
                           'GetManagedObjects',
                           None)
        
        partitions = []
        for item in objects:
            try:
                if 'block_devices'  in str(item):
                       drive = self.get_dbus_property('system',
                                        'org.freedesktop.UDisks2',
                                        item,
                                        'org.freedesktop.UDisks2.Block',
                                        'Drive')
                       if drive == '/': continue
                      
                       mountpoint = self.get_mountpoint(item)
                       if  mountpoint: continue

                       drive = str(drive).split('/')[-1]
                       part = str(item.split('/')[-1])
                       if not part[-1].isdigit(): continue
                       partitions.append((part,drive))                       
                       #print(partitions)

            except Exception as e:
                #print(e)
                pass

        partitions.sort()
        return partitions

    def get_dbus(self,bus_type,obj,path,interface,method,arg):
        if bus_type == "session":
            bus = dbus.SessionBus() 
        if bus_type == "system":
            bus = dbus.SystemBus()
        proxy = bus.get_object(obj,path)
        method = proxy.get_dbus_method(method,interface)
        if arg:
            return method(arg)
        else:
            return method()
    
    def get_dbus_property(self,bus_type,obj,path,iface,prop):

        if bus_type == "session":
           bus = dbus.SessionBus()
        if bus_type == "system":
           bus = dbus.SystemBus()
        proxy = bus.get_object(obj,path)
        aux = 'org.freedesktop.DBus.Properties'
        props_iface = dbus.Interface(proxy,aux)
        props = props_iface.Get(iface,prop)
        return props

    def make_alias(self,*args):
        partitions = [ i[0] for i in self.get_partitions() ]

        combo_values = '|'.join(partitions)
        command=[ 'zenity','--forms','--title','Make Alias',
                  '--add-combo','Partition','--combo-values',
                  combo_values,'--add-entry','Alias'    ]        
        user_input = self.run_cmd(command)
        if not user_input: return

        alias = user_input.decode().strip().split('|')

        existing_values = None
        if os.path.isfile(self.config_file):
            with open(self.config_file) as conf_file:
                try:
                    existing_values = json.load(conf_file)
                except ValueError:
                    pass
                    

        with open(self.config_file,'w') as conf_file:
             if existing_values:
                 existing_values[alias[0]] = alias[1]
             else:
                 existing_values = {alias[0]:alias[1]}
             json.dump(existing_values,conf_file,indent=4,sort_keys=True)
        

    def find_alias(self,part):
        if os.path.isfile(self.config_file):
            with open(self.config_file) as conf_file:
                try:
                    aliases = json.load(conf_file)
                except ValueError:
                    pass
                else:
                    if part in aliases:
                       return aliases[part]
                    else:
                       return None

    def toggle_auto_startup(self,*args):
        user_home = os.path.expanduser('~')
        desktop_file = '.config/autostart/udisks-indicator.desktop'
        full_path = os.path.join(user_home,desktop_file)

        if os.path.exists(full_path):
           os.unlink(full_path)
        else:
           original = '/usr/share/applications/udisks-indicator.desktop'
           if os.path.exists(original):
               shutil.copyfile(original,full_path)

        self.make_menu()


    def open_mountpoint(self,*args):
        pid = subprocess.Popen(['xdg-open',args[-1]]).pid

    def open_disks_utility(self,*args):
        pid = subprocess.Popen(['gnome-disks']).pid

    def gsettings_get(self, schema, path, key):
        """Get value of gsettings schema"""
        if path is None:
            gsettings = Gio.Settings.new(schema)
        else:
            gsettings = Gio.Settings.new_with_path(schema, path)
        return gsettings.get_value(key)

    def run_cmd(self, cmdlist):
        """ Reusable function for running external commands """
        new_env = dict(os.environ)
        new_env['LC_ALL'] = 'C'
        try:
            stdout = subprocess.check_output(cmdlist, env=new_env)
        except subprocess.CalledProcessError:
            pass
        else:
            if stdout:
                return stdout

    def run(self):
        """ Launches the indicator """
        try:
            gtk.main()
        except KeyboardInterrupt:
            pass

    def quit(self, data=None):
        """ closes indicator """
        gtk.main_quit()

def main():
    """ defines program entry point """
    indicator = UdisksIndicator()
    indicator.run()

if __name__ == '__main__':
    main()
